//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petshop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int IdOrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public Nullable<int> IdPickPoint { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickPoint PickPoint { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
