//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petshop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductArticleNumber { get; set; }
        public Nullable<int> IdProductName { get; set; }
        public Nullable<int> IdProductCategory { get; set; }
        public byte[] ProductImage { get; set; }
        public string Img { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<int> ProductSale { get; set; }
        public Nullable<int> ProductMaxSale { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public Nullable<int> IdProduser { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public string ProductStatus { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Produser Produser { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
